/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/schornFont/schornio_font.glb -t -T -o FontLogo.tsx 
Files: public/models/schornFont/schornio_font.glb [909.5KB] > C:\Users\mateu\OneDrive\Documentos\Coding\Schorn.io Codebase\space_traveler\schornio_font-transformed.glb [41.36KB] (95%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PATH_FONT_3D_MODELS } from "./path";

type GLTFResult = GLTF & {
  nodes: {
    schornio_full: THREE.Mesh;
  };
  materials: {
    Schornio_material: THREE.MeshStandardMaterial;
  };
};

export function FontLogo() {
  const { nodes, materials } = useGLTF(
    `${PATH_FONT_3D_MODELS}/schornio_font-transformed.glb`
  ) as GLTFResult;

  return (
    <group dispose={null}>
      <mesh
        geometry={nodes.schornio_full.geometry}
        material={materials.Schornio_material}
      />
    </group>
  );
}

useGLTF.preload(`${PATH_FONT_3D_MODELS}/schornio_font-transformed.glb`);
